# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: 
- name: "WhitespaceTokenizer"
  intent_split_symbol: "_"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
- name: "ResponseSelector"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FallbackPolicy
    # min confidence needed to accept an NLU prediction
    nlu_threshold: 0.1
    # min confidence needed to accept an action prediction from Rasa Core
    core_threshold: 0.1
    # name of the action to be called if the confidence of intent / action
    # is below the threshold
    fallback_action_name: 'action_my_fallback'
